"use client";
import {useEffect,useRef,useState} from 'react';
import {SUPABASE_URL,SUPABASE_KEY} from '../lib/supabase';
export default function PasswordRecovery(){
 const token=useRef('');const recoveryParams=useRef<URLSearchParams|null>(null);const [status,setStatus]=useState('checking');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const hash=recoveryParams.current||(recoveryParams.current=new URLSearchParams(location.hash.slice(1)));token.current=hash.get('access_token')||'';history.replaceState(null,'',location.pathname);if(hash.get('error')||!token.current){setStatus('invalid');return}
 fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token.current}}).then(r=>{if(active)setStatus(r.ok?'ready':'invalid')}).catch(()=>{if(active){setStatus('invalid');setError('Connexion impossible. Rouvrez le lien lorsque la connexion est rétablie.')}});return()=>{active=false}},[]);
 async function update(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const password=String(data.get('password')||'');if(password!==data.get('confirm')){setError('Les deux mots de passe doivent être identiques.');return}if(password.length<12){setError('Utilisez au moins 12 caractères.');return}setBusy(true);setError('');try{const r=await fetch(SUPABASE_URL+'/auth/v1/user',{method:'PUT',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token.current,'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json() as {msg?:string;message?:string};if(!r.ok)throw new Error(d.msg||d.message||'Le lien a expiré ou la modification a été refusée.');form.reset();sessionStorage.removeItem('noctys-session');setStatus('done');try{await fetch(SUPABASE_URL+'/auth/v1/logout?scope=global',{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token.current}})}catch{}token.current='';}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24}}><section className="panel" style={{width:'100%',maxWidth:470}}><a className="brand" href="/"><img src="/noctys.png" alt=""/>NOCTYS</a><h2 style={{marginTop:30}}>Nouveau mot de passe</h2>{status==='checking'?<p>Vérification du lien…</p>:status==='done'?<><p role="status">Votre mot de passe a été modifié. Connectez-vous avec votre pseudo et votre nouveau mot de passe.</p><a className="link-button primary" href="/">Retour à la connexion</a></>:status==='invalid'?<p role="alert">{error||'Ce lien de récupération est invalide ou expiré. Demandez un nouveau lien depuis Supabase.'}</p>:<form onSubmit={update}><label>Nouveau mot de passe<input name="password" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label><label>Confirmer le nouveau mot de passe<input name="confirm" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label>{error&&<p className="notice" role="alert">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Enregistrement…':'Enregistrer mon mot de passe'}</button></form>}</section></main>
}

